"""empty message

Revision ID: 2a8ec83e1d60
Revises: c50a72becc4
Create Date: 2014-05-31 21:18:56.672485

"""

# revision identifiers, used by Alembic.
revision = '2a8ec83e1d60'
down_revision = 'c50a72becc4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue', sa.Column('acknowledged_at', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue', 'acknowledged_at')
    ### end Alembic commands ###
